### ISSUE TITLE
can not be imported as "import polymorphic" (when polymorphic.py placed into the root namespace)

### ISSUE THREAD

**Issue by IlyaSemenov** [bconstantin/django_polymorphic#1]
My work setup is that I have a special directory for third party libraries which is added to sys.path. When I placed polymorphic.py into it and imported it from my app, it died:

```
File "/Users/semenov/Documents/workspace/corp/src/tracker/models.py", line 15, in <module>
  import polymorphic
File "/Users/semenov/work/ispl/polymorphic.py", line 956, in <module>
  class PolymorphicModel(models.Model):
File "/Users/semenov/work/ispl/polymorphic.py", line 878, in __new__
  new_class = super(PolymorphicModelBase, self).__new__(self, model_name, bases, attrs)
File "/Users/semenov/work/django/django/db/models/base.py", line 52, in __new__
  kwargs = {"app_label": model_module.__name__.split('.')[-2]}
IndexError: list index out of range
```

it worked fine as "from poly import polymorphic" but I find that setup a bit redundant.

This is Django 1.1.1 release.

**Comment by IlyaSemenov** [comment]
(Fixed formatting.)

**Comment by bconstantin** [comment]
I will check if I can reproduce this problem.

**Comment by bconstantin** [comment]
This is solved I believe. I will update the repository shortly.
Thanks, Bert.

**Comment by johnthedebs** [comment]
Can I ask what the issue is? I'm running into the same problem.

**Comment by bconstantin** [comment]
In django/db/models/base.py, line 50+ (Django 1.1.1), Django tries to determine the app_label for the model. This can't work if the module name does not contain '.'

This is why `model_module.__name__.split` fails.

polymorphic.py will contain a workaround (should arrive today or tomorrow).

It's somewhat related to these tickets:
http://code.djangoproject.com/ticket/1686
http://code.djangoproject.com/ticket/1658
http://code.djangoproject.com/ticket/3591
