### ISSUE TITLE
documentation replaced with spam

### ISSUE THREAD

**Issue by abeld** [bconstantin/django_polymorphic#11]
The Readme links to the docs on http://bserve.webhop.org/wiki/django_polymorphic/doc
but that wiki page is replaced by spam. The original page can be found in the page history, at http://bserve.webhop.org/wiki/django_polymorphic/doc?action=recall&rev=1 but I guess keeping the docs on a wiki that doesn't get spammed that bad would be a good idea.

**Comment by bconstantin** [comment]
Thanks! I have replaced the wiki with static pages.
