### ISSUE TITLE
Make .extra() only disable polymorphic query if an unsupported arg is used

### ISSUE THREAD

**Issue by abeld** [bconstantin/django_polymorphic#12]
Currently .extra() disables polymorphic queries by default, and requires the invoking code to explicitly enable them. I would like to suggest a bit more liberal approach: only disable them when an unsupported arg is used (according to the docs, 'order_by' and 'where' can be handled polymorphically).

The proposed changes are at 
http://github.com/abeld/django_polymorphic/commit/06528138e0adb8acb1f4f9b57e4ce802432fce18

The main reason I am suggesting this is because I am using django-polymorphic with  django-sortedm2m, and sortedm2m uses an .extra() call to construct a query. With current trunk of django-polymorphic, a sortedm2m field to a polymorphic model would return instances of the baseclass, instead of instances of the subclass, since polymorphic query gets turned off.

Keeping polymorphic queries enabled in this case improves compatibility between at least django-polymorphic and django-sortedm2m, making them work more out-of-the-box.

(Note that in the commit mentioned, I didn't update the documentation. Also I don't know how "experimental" the polymorphic .extra() is.)

**Comment by bconstantin** [comment]
I originally merged you proposed changes, but I grew doubts and backed them out again. I believe to have a solution now which should ensure compatibility with django-sortedm2m and similar usage patterns. I will include this into V1.0 beta2. It's basically a modified version of your patch.

**Comment by bconstantin** [comment]
extra() now works polymorphically (V1.0 Beta 2). This should resolve the problems. Please report if this is not the case.
