### ISSUE TITLE
Using non-integer keys results in subclasses not being returned in queries

### ISSUE THREAD

**Issue by mathieusteele** [bconstantin/django_polymorphic#14]
class Project(PolymorphicModel):
    topic = models.CharField(max_length = 30)

class ArtProject(Project):
    artist = models.CharField(max_length = 30)

class ResearchProject(Project):
    supervisor = models.CharField(max_length = 30)

The above works perfectly as expected.

The following allows creating any type of project, but UUIDProject.objects.all() returns only UUIDProject instances, no subclasses. The problem lies in non-integer keys. I have picked through the entire django_polymorphic package but have not yet been able to locate where non-integer keys cause the problem.

Additionally, objects with foreign keys pointing to UUIDProject can only be created for UUIDProject and not for its subclasses.

class UUIDProject(PolymorphicModel):
    id = UUIDField(primary_key = True)
    topic = models.CharField(max_length = 30)

class UUIDArtProject(UUIDProject):
    artist = models.CharField(max_length = 30)

class UUIDResearchProject(UUIDProject):
    supervisor = models.CharField(max_length = 30)

**Comment by bconstantin** [comment]
I tried to reproduce this problem with the UUIDField from django_extensions, but
UUIDProject.objects.all() works as it should in my tests.
Are you using UUIDField from django_extensions? If yes, it might be best if you put a code snippet which demonstrates this problem into django_polymorphic/pexp/management/commands/pcmd.py (you can execute this using 'python manage.py pexp', after syncdb). If no, which UUIDField do you use?

**Comment by bconstantin** [comment]
I forgot: Which version of django_polymorphic are you using?

**Comment by mathieusteele** [comment]
Bert:

http://gist.github.com/655314

Here is a gist of the uuidfield I am using. I will look at the django extensions version as the problem must lie within my implementation. To answer your followup question, I am on the latest version from yesterday 10-29-10.

**Comment by bconstantin** [comment]
I found it: django_polymorphic now generally uses "pk" instead of "id" to allow for other names of the primary key field.

For UUIDField, django however delivers different data types for UUIDField in derived models. "id" gives UUID and "pk" gives unicode.

You can fix this for now by adding the following hack to polymorphic/query.py, in the function get_real_instances:

http://gist.github.com/655410

I don't know right now if this also fixes the problem with foreign keys.

This looks like a bug in either UUIDField or Django.

**Comment by bconstantin** [comment]
I believe that V1.0 Beta 2 fixed this. Please reopen the issue if this is not the case.
Thanks, Bert
