### ISSUE TITLE
Incorrect behavior with multiple levels of inheritance

### ISSUE THREAD

**Issue by johnthedebs** [bconstantin/django_polymorphic#15]
There seems to be a regression introduced in this commit: a4ac6cc91d4f4f1263ed84d4af79a32cba553dbb

I set up two levels of inheritance, like so:

```
from django.db import models
from polymorphic import PolymorphicModel

class Top(PolymorphicModel):
    name = models.CharField(max_length=50)

class Middle(Top):
    description = models.TextField()

class Bottom(Middle):
    author = models.CharField(max_length=50)
```

And then do the following:

```
t = Top()
t.save()
m = Middle()
m.save()
b = Bottom()
b.save()

Top.objects.all()
Middle.objects.all()
Bottom.objects.all()
```

Expected output:
    [<Top: Top object>, <Bottom: Bottom object>, <Middle: Middle object>]
    [<Bottom: Bottom object>, <Middle: Middle object>]
    [<Bottom: Bottom object>]

Actual output:
    [<Top: Top object>, <Bottom: Bottom object>, <Middle: Middle object>]
    [<Middle: Middle object>]
    [<Bottom: Bottom object>]

Notice how Middle.objects.all() only returns instances of Middle, as opposed to instances of Middle and Bottom.

Let me know if any other info would be helpful.

**Comment by bconstantin** [comment]
Thanks for the precise bug report and the test case.
You were right with the commit that introduced the problem, therefore it was straightforward to track down and fix. The newest revision on github includes the fix.
