### ISSUE TITLE
"P classname" and "P appname" appear in the admin

### ISSUE THREAD

**Issue by IlyaSemenov** [bconstantin/django_polymorphic#2]
When I added my (derived) models as StackedInlines, two new undesireable fields appeared in the admin area: "P classname" and "P appname".

I suppose these two fields in PolymorphicModel should be marked as editable=False:

```
p_classname = models.CharField(max_length=100, default='')
p_appname = models.CharField(max_length=50, default='')
```

**Comment by bconstantin** [comment]
Seems fixed now. Thanks!
