### ISSUE TITLE
documentation not reachable

### ISSUE THREAD

**Issue by dmrschmidt** [bconstantin/django_polymorphic#22]
The "Quickstart" and "Installation and Usage Docs" from the README appear to be down since some time now.

**Comment by chrisglass** [comment]
Hi,

This fork (unfortunately it's still marked as the main one) is inactive for a long time now. For all we know the original author could be dead, or decided to live in a remote cave somewhere.

I maintain django_poymorphic for the time being, so I'll try to put a version of the docs online somehow.

In the mean time, please follow https://github.com/chrisglass/django_polymorphic instead.

Thanks for your understanding.

**Comment by dmrschmidt** [comment]
Ah good to know, thanks :)

**Comment by chrisglass** [comment]
It's not extremely active either, but I'll at least review and merge in patches, and discuss with people / try to help when I can. :)

**Comment by dmrschmidt** [comment]
I actually just stumbled upon this repository through django-shop and wanted to give it a try to see if it helps me out in some pain-in-the-ass situations ;) So some docs would have been great for that purpose. But I guess I could also dig into your django-shop implementation and study the test cases...

**Comment by chrisglass** [comment]
Yeah, that's an option. I just sent an email to github about bconstantin - not having docs online anymore is kind of annoying

**Comment by chrisglass** [comment]
Feel free to hop on #django-shop on freenode if you have quesitons - I'll try to help the best I can

**Comment by dmrschmidt** [comment]
Sweet, thanks a lot. If I run into any troubles when I start playing around with it I'll drop by on freenode :)
