### ISSUE TITLE
dumpdata improvement

### ISSUE THREAD

**Issue by ddanier** [bconstantin/django_polymorphic#27]
I have my own implementation of a polymorphic model and tend to look at what you have done here whenever I feel something getting tricky. Most of the time you have implemented nice solutions, so thumbs up. ;-)

Anyways, the dumpdata handling (https://github.com/bconstantin/django_polymorphic/blob/master/polymorphic/base.py#L171) seems hackish somehow. I did some research and found django has a _base_manager attribute (besides the _default_manager), which may be used for serialization. Don't know whether _base_manager was added in newer versions, but this fixed the dumpdata case for me. All needed is to add "_base_manager = base_objects" in the PolymorphicModel and then use "dumpdata -a" to tell Django to use _base_manager instead of _default_manager.

I tried to find why _base_manager was added and couldn't find out exactly what this is doing. But things work pretty well using _base_manager here and I couldn't find a usecase inside Django core which would have told me it shouldn't. So perhaps this helps django_polymorphic, too.

**Comment by vdboor** [comment]
Hi, FYI, please look at https://github.com/chrisglass/django_polymorphic, which has the latest version and proper dumpdata handling, see my note at #31 

(nowadays Django provides `--natural` to deal with FK's to `ContentType`)

Thanks for your time reporting this issue!
