### ISSUE TITLE
replace p_classname and p_appname with content_type_id or at least a single field

### ISSUE THREAD

**Issue by IlyaSemenov** [bconstantin/django_polymorphic#3]
Is there really no way to replace two varchars with one foreign key to django_contenttype? That would prevent the de-normalizing of a database.

Having varchars probably helps to reduce the number of database lookups against django_contenttypes, but even in that case, isn't that better to have just one (not two) CharField, storing "app.ModelName" strings? You seem to be always looking up p_appname and p_classname together, so that would actually clarify the code as well.

**Comment by bconstantin** [comment]
Hello Ilya, I agree with your suggestion, using ContentType looks like the best and cleanest solution indeed (I also considered app.ModelName, but ContentType clearly is better).
I will update the repository shortly.

**Comment by IlyaSemenov** [comment]
Thanks, works great!
