### ISSUE TITLE
performance improvement with select_related

### ISSUE THREAD

**Issue by ptone** [bconstantin/django_polymorphic#7]
I'm still digging hard to understand this - but is there now a chance for more optimization with 
http://code.djangoproject.com/changeset/12307

in that subclasses will have already been fetched in the case of select_related?

**Comment by bconstantin** [comment]
I tested this and unfortunately it doesn't seem to work for optimizing access to derived models. Right now, select_related doesn't seem to be useful for this kind of optimization.
