### ISSUE TITLE
Seeing some test fail

### ISSUE THREAD

**Issue by coleifer** [bconstantin/django_polymorphic#8]
This is the only polymorphic test i've got failing, wondered if anyone had the same or could replicate?
# 
## FAIL: test_annotate_aggregate_order (polymorphic.tests.testclass)

Traceback (most recent call last):
  File "/polymorphic/tests.py", line 151, in test_annotate_aggregate_order
    assert qs[0].entrycount == 2
AssertionError

---

**Comment by bconstantin** [comment]
I finally came around to install PostgreSQL, and there I finally get this, too. The reason seems to be that PostgresSQL returns the result entries in a different order than SQLite/MySQL. I will fix this in the test case code.
